### ISSUE TITLE
Server close when crafting the Dark Crystal Tools

### ISSUE THREAD

**Issue by IgnisTheGod** [0xmmalik/dark-crystal#7]
On crafting items made of dark crystals such as the sword, the server then suddenly closes.

Steps to reproduce the behavior: e.g., 
1. Craft Dark Crystal Sword

**Expected behavior**
The sword should've been crafted and that's it.

Crash log for the server provided 

[crash-2021-03-27_23.38.32-server.txt](https://github.com/0xmmalik/dark-crystal/files/6216607/crash-2021-03-27_23.38.32-server.txt)

**Comment by 0xmmalik** [comment]
What version of Minecraft are you using? What device are you on?

I recently became aware of an issue with the enchantment IDs because they change over multiple versions. Looking at the crash log, it does look like it's something to do with that, but if you could give me some more information on your Minecraft instance, that would be helpful.

**Comment by IgnisTheGod** [comment]
I'm on a windows on minecraft version 1.16.5

**Comment by 0xmmalik** [comment]
Perhaps it's something to do with it being a server or clashes with some of the other mods you have. I just tested it on 1.16.4 and it doesn't seem to crash (though it does apply the wrong enchantments, referring to the issues I mentioned earlier). Try crafting the tools in a singleplayer world with no other mods to make sure that's not the problem.

**Comment by 0xmmalik** [comment]
Does the tool-crafting work in singleplayer?
